version: "3.9"

services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  temporal-worker:
    volumes:
      - ./temporal:/app
    command: ["python", "-m", "src.worker"]
