{{- if and .Values.observability.enabled .Values.observability.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.opsApi.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: ops-api
    {{- with .Values.observability.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ops-api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.observability.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout | quote }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.temporalWorkerMetrics.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-worker-metrics
    {{- with .Values.observability.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: temporal-worker-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.observability.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
