/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as StorefrontCartRouteImport } from './routes/storefront/cart'
import { Route as RentalReturnsRouteImport } from './routes/rental/returns'
import { Route as RentalQuotingRouteImport } from './routes/rental/quoting'
import { Route as RentalProjectProposalRouteImport } from './routes/rental/project-proposal'
import { Route as RentalPortalFinancialsRouteImport } from './routes/rental/portal-financials'
import { Route as RentalInspectionComparisonRouteImport } from './routes/rental/inspection-comparison'
import { Route as RentalCounterReviewRouteImport } from './routes/rental/counter-review'
import { Route as RentalCatalogRouteImport } from './routes/rental/catalog'
import { Route as RentalAvailabilityRouteImport } from './routes/rental/availability'
import { Route as PortalStorefrontRouteImport } from './routes/portal/storefront'
import { Route as PortalRequestsRouteImport } from './routes/portal/requests'
import { Route as OpsTransfersRouteImport } from './routes/ops/transfers'
import { Route as OpsTechnicianMorningQueueRouteImport } from './routes/ops/technician-morning-queue'
import { Route as OpsShopMorningQueueRouteImport } from './routes/ops/shop-morning-queue'
import { Route as OpsRevenueRecognitionRouteImport } from './routes/ops/revenue-recognition'
import { Route as OpsLienDeadlinesRouteImport } from './routes/ops/lien-deadlines'
import { Route as OpsIncidentComplianceQueueRouteImport } from './routes/ops/incident-compliance-queue'
import { Route as OpsFleetRebalancingRouteImport } from './routes/ops/fleet-rebalancing'
import { Route as OpsFleetAuditsRouteImport } from './routes/ops/fleet-audits'
import { Route as OpsCreditReviewRouteImport } from './routes/ops/credit-review'
import { Route as OpsComplianceReadinessQueueRouteImport } from './routes/ops/compliance-readiness-queue'
import { Route as OpsCollectionsRouteImport } from './routes/ops/collections'
import { Route as OpsBillingUpdatesRouteImport } from './routes/ops/billing-updates'
import { Route as OpsAccountHealthQueueRouteImport } from './routes/ops/account-health-queue'
import { Route as InventoryKitsRouteImport } from './routes/inventory/kits'
import { Route as InventoryItemsRouteImport } from './routes/inventory/items'
import { Route as InventoryCalendarRouteImport } from './routes/inventory/calendar'
import { Route as FieldPodRouteImport } from './routes/field/pod'
import { Route as FieldMobileRouteImport } from './routes/field/mobile'
import { Route as FieldDispatchRouteImport } from './routes/field/dispatch'
import { Route as FieldCountsRouteImport } from './routes/field/counts'
import { Route as ExecutiveMonthlyOperatingPackRouteImport } from './routes/executive/monthly-operating-pack'
import { Route as EnterpriseOrgHierarchyRouteImport } from './routes/enterprise/org-hierarchy'
import { Route as DispatchYardRouteImport } from './routes/dispatch/yard'
import { Route as DispatchPredispatchRouteImport } from './routes/dispatch/predispatch'
import { Route as DispatchLiveRouteImport } from './routes/dispatch/live'
import { Route as DispatchComplaintsRouteImport } from './routes/dispatch/complaints'
import { Route as BranchOpsRouteImport } from './routes/branch/ops'
import { Route as BranchMorningBriefRouteImport } from './routes/branch/morning-brief'
import { Route as BranchMonthlyPackRouteImport } from './routes/branch/monthly-pack'
import { Route as BranchCountsRouteImport } from './routes/branch/counts'
import { Route as AnalyticsTransportRouteImport } from './routes/analytics/transport'
import { Route as AnalyticsTaxFilingsRouteImport } from './routes/analytics/tax-filings'
import { Route as AnalyticsSafetyRouteImport } from './routes/analytics/safety'
import { Route as AnalyticsFleetRouteImport } from './routes/analytics/fleet'
import { Route as AnalyticsEnterpriseFinancialsRouteImport } from './routes/analytics/enterprise-financials'
import { Route as AnalyticsDashboardsRouteImport } from './routes/analytics/dashboards'
import { Route as AnalyticsAiReportingRouteImport } from './routes/analytics/ai-reporting'
import { Route as AccountingGeneralLedgerRouteImport } from './routes/accounting/general-ledger'
import { Route as AccountingExportConfigRouteImport } from './routes/accounting/export-config'
import { Route as RentalOrdersIndexRouteImport } from './routes/rental/orders/index'
import { Route as RentalContractsIndexRouteImport } from './routes/rental/contracts/index'
import { Route as OpsFindingsIndexRouteImport } from './routes/ops/findings/index'
import { Route as EntitiesEntityTypeIndexRouteImport } from './routes/entities/$entityType/index'
import { Route as CrmCustomersIndexRouteImport } from './routes/crm/customers/index'
import { Route as RentalOrdersIdRouteImport } from './routes/rental/orders/$id'
import { Route as RentalContractsIdRouteImport } from './routes/rental/contracts/$id'
import { Route as PortalScheduleContractIdRouteImport } from './routes/portal/schedule/$contractId'
import { Route as PortalIntakeTokenIdRouteImport } from './routes/portal/intake/$tokenId'
import { Route as PortalCatalogJobSiteIdRouteImport } from './routes/portal/catalog/$jobSiteId'
import { Route as PortalBillingUpdateTokenIdRouteImport } from './routes/portal/billing-update/$tokenId'
import { Route as OpsFindingsFindingIdRouteImport } from './routes/ops/findings/$findingId'
import { Route as OpsAuditEntityIdRouteImport } from './routes/ops/audit/$entityId'
import { Route as EntitiesEntityTypeIdRouteImport } from './routes/entities/$entityType/$id'
import { Route as CrmCustomersIdRouteImport } from './routes/crm/customers/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontCartRoute = StorefrontCartRouteImport.update({
  id: '/storefront/cart',
  path: '/storefront/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalReturnsRoute = RentalReturnsRouteImport.update({
  id: '/rental/returns',
  path: '/rental/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalQuotingRoute = RentalQuotingRouteImport.update({
  id: '/rental/quoting',
  path: '/rental/quoting',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalProjectProposalRoute = RentalProjectProposalRouteImport.update({
  id: '/rental/project-proposal',
  path: '/rental/project-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalPortalFinancialsRoute = RentalPortalFinancialsRouteImport.update({
  id: '/rental/portal-financials',
  path: '/rental/portal-financials',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalInspectionComparisonRoute =
  RentalInspectionComparisonRouteImport.update({
    id: '/rental/inspection-comparison',
    path: '/rental/inspection-comparison',
    getParentRoute: () => rootRouteImport,
  } as any)
const RentalCounterReviewRoute = RentalCounterReviewRouteImport.update({
  id: '/rental/counter-review',
  path: '/rental/counter-review',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalCatalogRoute = RentalCatalogRouteImport.update({
  id: '/rental/catalog',
  path: '/rental/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalAvailabilityRoute = RentalAvailabilityRouteImport.update({
  id: '/rental/availability',
  path: '/rental/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStorefrontRoute = PortalStorefrontRouteImport.update({
  id: '/portal/storefront',
  path: '/portal/storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRequestsRoute = PortalRequestsRouteImport.update({
  id: '/portal/requests',
  path: '/portal/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsTransfersRoute = OpsTransfersRouteImport.update({
  id: '/ops/transfers',
  path: '/ops/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsTechnicianMorningQueueRoute =
  OpsTechnicianMorningQueueRouteImport.update({
    id: '/ops/technician-morning-queue',
    path: '/ops/technician-morning-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpsShopMorningQueueRoute = OpsShopMorningQueueRouteImport.update({
  id: '/ops/shop-morning-queue',
  path: '/ops/shop-morning-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRevenueRecognitionRoute = OpsRevenueRecognitionRouteImport.update({
  id: '/ops/revenue-recognition',
  path: '/ops/revenue-recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsLienDeadlinesRoute = OpsLienDeadlinesRouteImport.update({
  id: '/ops/lien-deadlines',
  path: '/ops/lien-deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIncidentComplianceQueueRoute =
  OpsIncidentComplianceQueueRouteImport.update({
    id: '/ops/incident-compliance-queue',
    path: '/ops/incident-compliance-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpsFleetRebalancingRoute = OpsFleetRebalancingRouteImport.update({
  id: '/ops/fleet-rebalancing',
  path: '/ops/fleet-rebalancing',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsFleetAuditsRoute = OpsFleetAuditsRouteImport.update({
  id: '/ops/fleet-audits',
  path: '/ops/fleet-audits',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsCreditReviewRoute = OpsCreditReviewRouteImport.update({
  id: '/ops/credit-review',
  path: '/ops/credit-review',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsComplianceReadinessQueueRoute =
  OpsComplianceReadinessQueueRouteImport.update({
    id: '/ops/compliance-readiness-queue',
    path: '/ops/compliance-readiness-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpsCollectionsRoute = OpsCollectionsRouteImport.update({
  id: '/ops/collections',
  path: '/ops/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsBillingUpdatesRoute = OpsBillingUpdatesRouteImport.update({
  id: '/ops/billing-updates',
  path: '/ops/billing-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsAccountHealthQueueRoute = OpsAccountHealthQueueRouteImport.update({
  id: '/ops/account-health-queue',
  path: '/ops/account-health-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryKitsRoute = InventoryKitsRouteImport.update({
  id: '/inventory/kits',
  path: '/inventory/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryCalendarRoute = InventoryCalendarRouteImport.update({
  id: '/inventory/calendar',
  path: '/inventory/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldPodRoute = FieldPodRouteImport.update({
  id: '/field/pod',
  path: '/field/pod',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldMobileRoute = FieldMobileRouteImport.update({
  id: '/field/mobile',
  path: '/field/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldDispatchRoute = FieldDispatchRouteImport.update({
  id: '/field/dispatch',
  path: '/field/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldCountsRoute = FieldCountsRouteImport.update({
  id: '/field/counts',
  path: '/field/counts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveMonthlyOperatingPackRoute =
  ExecutiveMonthlyOperatingPackRouteImport.update({
    id: '/executive/monthly-operating-pack',
    path: '/executive/monthly-operating-pack',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnterpriseOrgHierarchyRoute = EnterpriseOrgHierarchyRouteImport.update({
  id: '/enterprise/org-hierarchy',
  path: '/enterprise/org-hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchYardRoute = DispatchYardRouteImport.update({
  id: '/dispatch/yard',
  path: '/dispatch/yard',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchPredispatchRoute = DispatchPredispatchRouteImport.update({
  id: '/dispatch/predispatch',
  path: '/dispatch/predispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchLiveRoute = DispatchLiveRouteImport.update({
  id: '/dispatch/live',
  path: '/dispatch/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchComplaintsRoute = DispatchComplaintsRouteImport.update({
  id: '/dispatch/complaints',
  path: '/dispatch/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchOpsRoute = BranchOpsRouteImport.update({
  id: '/branch/ops',
  path: '/branch/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchMorningBriefRoute = BranchMorningBriefRouteImport.update({
  id: '/branch/morning-brief',
  path: '/branch/morning-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchMonthlyPackRoute = BranchMonthlyPackRouteImport.update({
  id: '/branch/monthly-pack',
  path: '/branch/monthly-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchCountsRoute = BranchCountsRouteImport.update({
  id: '/branch/counts',
  path: '/branch/counts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsTransportRoute = AnalyticsTransportRouteImport.update({
  id: '/analytics/transport',
  path: '/analytics/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsTaxFilingsRoute = AnalyticsTaxFilingsRouteImport.update({
  id: '/analytics/tax-filings',
  path: '/analytics/tax-filings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSafetyRoute = AnalyticsSafetyRouteImport.update({
  id: '/analytics/safety',
  path: '/analytics/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsFleetRoute = AnalyticsFleetRouteImport.update({
  id: '/analytics/fleet',
  path: '/analytics/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsEnterpriseFinancialsRoute =
  AnalyticsEnterpriseFinancialsRouteImport.update({
    id: '/analytics/enterprise-financials',
    path: '/analytics/enterprise-financials',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnalyticsDashboardsRoute = AnalyticsDashboardsRouteImport.update({
  id: '/analytics/dashboards',
  path: '/analytics/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsAiReportingRoute = AnalyticsAiReportingRouteImport.update({
  id: '/analytics/ai-reporting',
  path: '/analytics/ai-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingGeneralLedgerRoute = AccountingGeneralLedgerRouteImport.update({
  id: '/accounting/general-ledger',
  path: '/accounting/general-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingExportConfigRoute = AccountingExportConfigRouteImport.update({
  id: '/accounting/export-config',
  path: '/accounting/export-config',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalOrdersIndexRoute = RentalOrdersIndexRouteImport.update({
  id: '/rental/orders/',
  path: '/rental/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalContractsIndexRoute = RentalContractsIndexRouteImport.update({
  id: '/rental/contracts/',
  path: '/rental/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsFindingsIndexRoute = OpsFindingsIndexRouteImport.update({
  id: '/ops/findings/',
  path: '/ops/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIndexRoute = EntitiesEntityTypeIndexRouteImport.update({
  id: '/entities/$entityType/',
  path: '/entities/$entityType/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersIndexRoute = CrmCustomersIndexRouteImport.update({
  id: '/crm/customers/',
  path: '/crm/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalOrdersIdRoute = RentalOrdersIdRouteImport.update({
  id: '/rental/orders/$id',
  path: '/rental/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalContractsIdRoute = RentalContractsIdRouteImport.update({
  id: '/rental/contracts/$id',
  path: '/rental/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalScheduleContractIdRoute =
  PortalScheduleContractIdRouteImport.update({
    id: '/portal/schedule/$contractId',
    path: '/portal/schedule/$contractId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalIntakeTokenIdRoute = PortalIntakeTokenIdRouteImport.update({
  id: '/portal/intake/$tokenId',
  path: '/portal/intake/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCatalogJobSiteIdRoute = PortalCatalogJobSiteIdRouteImport.update({
  id: '/portal/catalog/$jobSiteId',
  path: '/portal/catalog/$jobSiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBillingUpdateTokenIdRoute =
  PortalBillingUpdateTokenIdRouteImport.update({
    id: '/portal/billing-update/$tokenId',
    path: '/portal/billing-update/$tokenId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpsFindingsFindingIdRoute = OpsFindingsFindingIdRouteImport.update({
  id: '/ops/findings/$findingId',
  path: '/ops/findings/$findingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsAuditEntityIdRoute = OpsAuditEntityIdRouteImport.update({
  id: '/ops/audit/$entityId',
  path: '/ops/audit/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIdRoute = EntitiesEntityTypeIdRouteImport.update({
  id: '/entities/$entityType/$id',
  path: '/entities/$entityType/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersIdRoute = CrmCustomersIdRouteImport.update({
  id: '/crm/customers/$id',
  path: '/crm/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounting/export-config': typeof AccountingExportConfigRoute
  '/accounting/general-ledger': typeof AccountingGeneralLedgerRoute
  '/analytics/ai-reporting': typeof AnalyticsAiReportingRoute
  '/analytics/dashboards': typeof AnalyticsDashboardsRoute
  '/analytics/enterprise-financials': typeof AnalyticsEnterpriseFinancialsRoute
  '/analytics/fleet': typeof AnalyticsFleetRoute
  '/analytics/safety': typeof AnalyticsSafetyRoute
  '/analytics/tax-filings': typeof AnalyticsTaxFilingsRoute
  '/analytics/transport': typeof AnalyticsTransportRoute
  '/branch/counts': typeof BranchCountsRoute
  '/branch/monthly-pack': typeof BranchMonthlyPackRoute
  '/branch/morning-brief': typeof BranchMorningBriefRoute
  '/branch/ops': typeof BranchOpsRoute
  '/dispatch/complaints': typeof DispatchComplaintsRoute
  '/dispatch/live': typeof DispatchLiveRoute
  '/dispatch/predispatch': typeof DispatchPredispatchRoute
  '/dispatch/yard': typeof DispatchYardRoute
  '/enterprise/org-hierarchy': typeof EnterpriseOrgHierarchyRoute
  '/executive/monthly-operating-pack': typeof ExecutiveMonthlyOperatingPackRoute
  '/field/counts': typeof FieldCountsRoute
  '/field/dispatch': typeof FieldDispatchRoute
  '/field/mobile': typeof FieldMobileRoute
  '/field/pod': typeof FieldPodRoute
  '/inventory/calendar': typeof InventoryCalendarRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/kits': typeof InventoryKitsRoute
  '/ops/account-health-queue': typeof OpsAccountHealthQueueRoute
  '/ops/billing-updates': typeof OpsBillingUpdatesRoute
  '/ops/collections': typeof OpsCollectionsRoute
  '/ops/compliance-readiness-queue': typeof OpsComplianceReadinessQueueRoute
  '/ops/credit-review': typeof OpsCreditReviewRoute
  '/ops/fleet-audits': typeof OpsFleetAuditsRoute
  '/ops/fleet-rebalancing': typeof OpsFleetRebalancingRoute
  '/ops/incident-compliance-queue': typeof OpsIncidentComplianceQueueRoute
  '/ops/lien-deadlines': typeof OpsLienDeadlinesRoute
  '/ops/revenue-recognition': typeof OpsRevenueRecognitionRoute
  '/ops/shop-morning-queue': typeof OpsShopMorningQueueRoute
  '/ops/technician-morning-queue': typeof OpsTechnicianMorningQueueRoute
  '/ops/transfers': typeof OpsTransfersRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/storefront': typeof PortalStorefrontRoute
  '/rental/availability': typeof RentalAvailabilityRoute
  '/rental/catalog': typeof RentalCatalogRoute
  '/rental/counter-review': typeof RentalCounterReviewRoute
  '/rental/inspection-comparison': typeof RentalInspectionComparisonRoute
  '/rental/portal-financials': typeof RentalPortalFinancialsRoute
  '/rental/project-proposal': typeof RentalProjectProposalRoute
  '/rental/quoting': typeof RentalQuotingRoute
  '/rental/returns': typeof RentalReturnsRoute
  '/storefront/cart': typeof StorefrontCartRoute
  '/ops/': typeof OpsIndexRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/ops/audit/$entityId': typeof OpsAuditEntityIdRoute
  '/ops/findings/$findingId': typeof OpsFindingsFindingIdRoute
  '/portal/billing-update/$tokenId': typeof PortalBillingUpdateTokenIdRoute
  '/portal/catalog/$jobSiteId': typeof PortalCatalogJobSiteIdRoute
  '/portal/intake/$tokenId': typeof PortalIntakeTokenIdRoute
  '/portal/schedule/$contractId': typeof PortalScheduleContractIdRoute
  '/rental/contracts/$id': typeof RentalContractsIdRoute
  '/rental/orders/$id': typeof RentalOrdersIdRoute
  '/crm/customers/': typeof CrmCustomersIndexRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
  '/ops/findings/': typeof OpsFindingsIndexRoute
  '/rental/contracts/': typeof RentalContractsIndexRoute
  '/rental/orders/': typeof RentalOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounting/export-config': typeof AccountingExportConfigRoute
  '/accounting/general-ledger': typeof AccountingGeneralLedgerRoute
  '/analytics/ai-reporting': typeof AnalyticsAiReportingRoute
  '/analytics/dashboards': typeof AnalyticsDashboardsRoute
  '/analytics/enterprise-financials': typeof AnalyticsEnterpriseFinancialsRoute
  '/analytics/fleet': typeof AnalyticsFleetRoute
  '/analytics/safety': typeof AnalyticsSafetyRoute
  '/analytics/tax-filings': typeof AnalyticsTaxFilingsRoute
  '/analytics/transport': typeof AnalyticsTransportRoute
  '/branch/counts': typeof BranchCountsRoute
  '/branch/monthly-pack': typeof BranchMonthlyPackRoute
  '/branch/morning-brief': typeof BranchMorningBriefRoute
  '/branch/ops': typeof BranchOpsRoute
  '/dispatch/complaints': typeof DispatchComplaintsRoute
  '/dispatch/live': typeof DispatchLiveRoute
  '/dispatch/predispatch': typeof DispatchPredispatchRoute
  '/dispatch/yard': typeof DispatchYardRoute
  '/enterprise/org-hierarchy': typeof EnterpriseOrgHierarchyRoute
  '/executive/monthly-operating-pack': typeof ExecutiveMonthlyOperatingPackRoute
  '/field/counts': typeof FieldCountsRoute
  '/field/dispatch': typeof FieldDispatchRoute
  '/field/mobile': typeof FieldMobileRoute
  '/field/pod': typeof FieldPodRoute
  '/inventory/calendar': typeof InventoryCalendarRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/kits': typeof InventoryKitsRoute
  '/ops/account-health-queue': typeof OpsAccountHealthQueueRoute
  '/ops/billing-updates': typeof OpsBillingUpdatesRoute
  '/ops/collections': typeof OpsCollectionsRoute
  '/ops/compliance-readiness-queue': typeof OpsComplianceReadinessQueueRoute
  '/ops/credit-review': typeof OpsCreditReviewRoute
  '/ops/fleet-audits': typeof OpsFleetAuditsRoute
  '/ops/fleet-rebalancing': typeof OpsFleetRebalancingRoute
  '/ops/incident-compliance-queue': typeof OpsIncidentComplianceQueueRoute
  '/ops/lien-deadlines': typeof OpsLienDeadlinesRoute
  '/ops/revenue-recognition': typeof OpsRevenueRecognitionRoute
  '/ops/shop-morning-queue': typeof OpsShopMorningQueueRoute
  '/ops/technician-morning-queue': typeof OpsTechnicianMorningQueueRoute
  '/ops/transfers': typeof OpsTransfersRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/storefront': typeof PortalStorefrontRoute
  '/rental/availability': typeof RentalAvailabilityRoute
  '/rental/catalog': typeof RentalCatalogRoute
  '/rental/counter-review': typeof RentalCounterReviewRoute
  '/rental/inspection-comparison': typeof RentalInspectionComparisonRoute
  '/rental/portal-financials': typeof RentalPortalFinancialsRoute
  '/rental/project-proposal': typeof RentalProjectProposalRoute
  '/rental/quoting': typeof RentalQuotingRoute
  '/rental/returns': typeof RentalReturnsRoute
  '/storefront/cart': typeof StorefrontCartRoute
  '/ops': typeof OpsIndexRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/ops/audit/$entityId': typeof OpsAuditEntityIdRoute
  '/ops/findings/$findingId': typeof OpsFindingsFindingIdRoute
  '/portal/billing-update/$tokenId': typeof PortalBillingUpdateTokenIdRoute
  '/portal/catalog/$jobSiteId': typeof PortalCatalogJobSiteIdRoute
  '/portal/intake/$tokenId': typeof PortalIntakeTokenIdRoute
  '/portal/schedule/$contractId': typeof PortalScheduleContractIdRoute
  '/rental/contracts/$id': typeof RentalContractsIdRoute
  '/rental/orders/$id': typeof RentalOrdersIdRoute
  '/crm/customers': typeof CrmCustomersIndexRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
  '/ops/findings': typeof OpsFindingsIndexRoute
  '/rental/contracts': typeof RentalContractsIndexRoute
  '/rental/orders': typeof RentalOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounting/export-config': typeof AccountingExportConfigRoute
  '/accounting/general-ledger': typeof AccountingGeneralLedgerRoute
  '/analytics/ai-reporting': typeof AnalyticsAiReportingRoute
  '/analytics/dashboards': typeof AnalyticsDashboardsRoute
  '/analytics/enterprise-financials': typeof AnalyticsEnterpriseFinancialsRoute
  '/analytics/fleet': typeof AnalyticsFleetRoute
  '/analytics/safety': typeof AnalyticsSafetyRoute
  '/analytics/tax-filings': typeof AnalyticsTaxFilingsRoute
  '/analytics/transport': typeof AnalyticsTransportRoute
  '/branch/counts': typeof BranchCountsRoute
  '/branch/monthly-pack': typeof BranchMonthlyPackRoute
  '/branch/morning-brief': typeof BranchMorningBriefRoute
  '/branch/ops': typeof BranchOpsRoute
  '/dispatch/complaints': typeof DispatchComplaintsRoute
  '/dispatch/live': typeof DispatchLiveRoute
  '/dispatch/predispatch': typeof DispatchPredispatchRoute
  '/dispatch/yard': typeof DispatchYardRoute
  '/enterprise/org-hierarchy': typeof EnterpriseOrgHierarchyRoute
  '/executive/monthly-operating-pack': typeof ExecutiveMonthlyOperatingPackRoute
  '/field/counts': typeof FieldCountsRoute
  '/field/dispatch': typeof FieldDispatchRoute
  '/field/mobile': typeof FieldMobileRoute
  '/field/pod': typeof FieldPodRoute
  '/inventory/calendar': typeof InventoryCalendarRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/kits': typeof InventoryKitsRoute
  '/ops/account-health-queue': typeof OpsAccountHealthQueueRoute
  '/ops/billing-updates': typeof OpsBillingUpdatesRoute
  '/ops/collections': typeof OpsCollectionsRoute
  '/ops/compliance-readiness-queue': typeof OpsComplianceReadinessQueueRoute
  '/ops/credit-review': typeof OpsCreditReviewRoute
  '/ops/fleet-audits': typeof OpsFleetAuditsRoute
  '/ops/fleet-rebalancing': typeof OpsFleetRebalancingRoute
  '/ops/incident-compliance-queue': typeof OpsIncidentComplianceQueueRoute
  '/ops/lien-deadlines': typeof OpsLienDeadlinesRoute
  '/ops/revenue-recognition': typeof OpsRevenueRecognitionRoute
  '/ops/shop-morning-queue': typeof OpsShopMorningQueueRoute
  '/ops/technician-morning-queue': typeof OpsTechnicianMorningQueueRoute
  '/ops/transfers': typeof OpsTransfersRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/portal/storefront': typeof PortalStorefrontRoute
  '/rental/availability': typeof RentalAvailabilityRoute
  '/rental/catalog': typeof RentalCatalogRoute
  '/rental/counter-review': typeof RentalCounterReviewRoute
  '/rental/inspection-comparison': typeof RentalInspectionComparisonRoute
  '/rental/portal-financials': typeof RentalPortalFinancialsRoute
  '/rental/project-proposal': typeof RentalProjectProposalRoute
  '/rental/quoting': typeof RentalQuotingRoute
  '/rental/returns': typeof RentalReturnsRoute
  '/storefront/cart': typeof StorefrontCartRoute
  '/ops/': typeof OpsIndexRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/ops/audit/$entityId': typeof OpsAuditEntityIdRoute
  '/ops/findings/$findingId': typeof OpsFindingsFindingIdRoute
  '/portal/billing-update/$tokenId': typeof PortalBillingUpdateTokenIdRoute
  '/portal/catalog/$jobSiteId': typeof PortalCatalogJobSiteIdRoute
  '/portal/intake/$tokenId': typeof PortalIntakeTokenIdRoute
  '/portal/schedule/$contractId': typeof PortalScheduleContractIdRoute
  '/rental/contracts/$id': typeof RentalContractsIdRoute
  '/rental/orders/$id': typeof RentalOrdersIdRoute
  '/crm/customers/': typeof CrmCustomersIndexRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
  '/ops/findings/': typeof OpsFindingsIndexRoute
  '/rental/contracts/': typeof RentalContractsIndexRoute
  '/rental/orders/': typeof RentalOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounting/export-config'
    | '/accounting/general-ledger'
    | '/analytics/ai-reporting'
    | '/analytics/dashboards'
    | '/analytics/enterprise-financials'
    | '/analytics/fleet'
    | '/analytics/safety'
    | '/analytics/tax-filings'
    | '/analytics/transport'
    | '/branch/counts'
    | '/branch/monthly-pack'
    | '/branch/morning-brief'
    | '/branch/ops'
    | '/dispatch/complaints'
    | '/dispatch/live'
    | '/dispatch/predispatch'
    | '/dispatch/yard'
    | '/enterprise/org-hierarchy'
    | '/executive/monthly-operating-pack'
    | '/field/counts'
    | '/field/dispatch'
    | '/field/mobile'
    | '/field/pod'
    | '/inventory/calendar'
    | '/inventory/items'
    | '/inventory/kits'
    | '/ops/account-health-queue'
    | '/ops/billing-updates'
    | '/ops/collections'
    | '/ops/compliance-readiness-queue'
    | '/ops/credit-review'
    | '/ops/fleet-audits'
    | '/ops/fleet-rebalancing'
    | '/ops/incident-compliance-queue'
    | '/ops/lien-deadlines'
    | '/ops/revenue-recognition'
    | '/ops/shop-morning-queue'
    | '/ops/technician-morning-queue'
    | '/ops/transfers'
    | '/portal/requests'
    | '/portal/storefront'
    | '/rental/availability'
    | '/rental/catalog'
    | '/rental/counter-review'
    | '/rental/inspection-comparison'
    | '/rental/portal-financials'
    | '/rental/project-proposal'
    | '/rental/quoting'
    | '/rental/returns'
    | '/storefront/cart'
    | '/ops/'
    | '/crm/customers/$id'
    | '/entities/$entityType/$id'
    | '/ops/audit/$entityId'
    | '/ops/findings/$findingId'
    | '/portal/billing-update/$tokenId'
    | '/portal/catalog/$jobSiteId'
    | '/portal/intake/$tokenId'
    | '/portal/schedule/$contractId'
    | '/rental/contracts/$id'
    | '/rental/orders/$id'
    | '/crm/customers/'
    | '/entities/$entityType/'
    | '/ops/findings/'
    | '/rental/contracts/'
    | '/rental/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounting/export-config'
    | '/accounting/general-ledger'
    | '/analytics/ai-reporting'
    | '/analytics/dashboards'
    | '/analytics/enterprise-financials'
    | '/analytics/fleet'
    | '/analytics/safety'
    | '/analytics/tax-filings'
    | '/analytics/transport'
    | '/branch/counts'
    | '/branch/monthly-pack'
    | '/branch/morning-brief'
    | '/branch/ops'
    | '/dispatch/complaints'
    | '/dispatch/live'
    | '/dispatch/predispatch'
    | '/dispatch/yard'
    | '/enterprise/org-hierarchy'
    | '/executive/monthly-operating-pack'
    | '/field/counts'
    | '/field/dispatch'
    | '/field/mobile'
    | '/field/pod'
    | '/inventory/calendar'
    | '/inventory/items'
    | '/inventory/kits'
    | '/ops/account-health-queue'
    | '/ops/billing-updates'
    | '/ops/collections'
    | '/ops/compliance-readiness-queue'
    | '/ops/credit-review'
    | '/ops/fleet-audits'
    | '/ops/fleet-rebalancing'
    | '/ops/incident-compliance-queue'
    | '/ops/lien-deadlines'
    | '/ops/revenue-recognition'
    | '/ops/shop-morning-queue'
    | '/ops/technician-morning-queue'
    | '/ops/transfers'
    | '/portal/requests'
    | '/portal/storefront'
    | '/rental/availability'
    | '/rental/catalog'
    | '/rental/counter-review'
    | '/rental/inspection-comparison'
    | '/rental/portal-financials'
    | '/rental/project-proposal'
    | '/rental/quoting'
    | '/rental/returns'
    | '/storefront/cart'
    | '/ops'
    | '/crm/customers/$id'
    | '/entities/$entityType/$id'
    | '/ops/audit/$entityId'
    | '/ops/findings/$findingId'
    | '/portal/billing-update/$tokenId'
    | '/portal/catalog/$jobSiteId'
    | '/portal/intake/$tokenId'
    | '/portal/schedule/$contractId'
    | '/rental/contracts/$id'
    | '/rental/orders/$id'
    | '/crm/customers'
    | '/entities/$entityType'
    | '/ops/findings'
    | '/rental/contracts'
    | '/rental/orders'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/accounting/export-config'
    | '/accounting/general-ledger'
    | '/analytics/ai-reporting'
    | '/analytics/dashboards'
    | '/analytics/enterprise-financials'
    | '/analytics/fleet'
    | '/analytics/safety'
    | '/analytics/tax-filings'
    | '/analytics/transport'
    | '/branch/counts'
    | '/branch/monthly-pack'
    | '/branch/morning-brief'
    | '/branch/ops'
    | '/dispatch/complaints'
    | '/dispatch/live'
    | '/dispatch/predispatch'
    | '/dispatch/yard'
    | '/enterprise/org-hierarchy'
    | '/executive/monthly-operating-pack'
    | '/field/counts'
    | '/field/dispatch'
    | '/field/mobile'
    | '/field/pod'
    | '/inventory/calendar'
    | '/inventory/items'
    | '/inventory/kits'
    | '/ops/account-health-queue'
    | '/ops/billing-updates'
    | '/ops/collections'
    | '/ops/compliance-readiness-queue'
    | '/ops/credit-review'
    | '/ops/fleet-audits'
    | '/ops/fleet-rebalancing'
    | '/ops/incident-compliance-queue'
    | '/ops/lien-deadlines'
    | '/ops/revenue-recognition'
    | '/ops/shop-morning-queue'
    | '/ops/technician-morning-queue'
    | '/ops/transfers'
    | '/portal/requests'
    | '/portal/storefront'
    | '/rental/availability'
    | '/rental/catalog'
    | '/rental/counter-review'
    | '/rental/inspection-comparison'
    | '/rental/portal-financials'
    | '/rental/project-proposal'
    | '/rental/quoting'
    | '/rental/returns'
    | '/storefront/cart'
    | '/ops/'
    | '/crm/customers/$id'
    | '/entities/$entityType/$id'
    | '/ops/audit/$entityId'
    | '/ops/findings/$findingId'
    | '/portal/billing-update/$tokenId'
    | '/portal/catalog/$jobSiteId'
    | '/portal/intake/$tokenId'
    | '/portal/schedule/$contractId'
    | '/rental/contracts/$id'
    | '/rental/orders/$id'
    | '/crm/customers/'
    | '/entities/$entityType/'
    | '/ops/findings/'
    | '/rental/contracts/'
    | '/rental/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AccountingExportConfigRoute: typeof AccountingExportConfigRoute
  AccountingGeneralLedgerRoute: typeof AccountingGeneralLedgerRoute
  AnalyticsAiReportingRoute: typeof AnalyticsAiReportingRoute
  AnalyticsDashboardsRoute: typeof AnalyticsDashboardsRoute
  AnalyticsEnterpriseFinancialsRoute: typeof AnalyticsEnterpriseFinancialsRoute
  AnalyticsFleetRoute: typeof AnalyticsFleetRoute
  AnalyticsSafetyRoute: typeof AnalyticsSafetyRoute
  AnalyticsTaxFilingsRoute: typeof AnalyticsTaxFilingsRoute
  AnalyticsTransportRoute: typeof AnalyticsTransportRoute
  BranchCountsRoute: typeof BranchCountsRoute
  BranchMonthlyPackRoute: typeof BranchMonthlyPackRoute
  BranchMorningBriefRoute: typeof BranchMorningBriefRoute
  BranchOpsRoute: typeof BranchOpsRoute
  DispatchComplaintsRoute: typeof DispatchComplaintsRoute
  DispatchLiveRoute: typeof DispatchLiveRoute
  DispatchPredispatchRoute: typeof DispatchPredispatchRoute
  DispatchYardRoute: typeof DispatchYardRoute
  EnterpriseOrgHierarchyRoute: typeof EnterpriseOrgHierarchyRoute
  ExecutiveMonthlyOperatingPackRoute: typeof ExecutiveMonthlyOperatingPackRoute
  FieldCountsRoute: typeof FieldCountsRoute
  FieldDispatchRoute: typeof FieldDispatchRoute
  FieldMobileRoute: typeof FieldMobileRoute
  FieldPodRoute: typeof FieldPodRoute
  InventoryCalendarRoute: typeof InventoryCalendarRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  InventoryKitsRoute: typeof InventoryKitsRoute
  OpsAccountHealthQueueRoute: typeof OpsAccountHealthQueueRoute
  OpsBillingUpdatesRoute: typeof OpsBillingUpdatesRoute
  OpsCollectionsRoute: typeof OpsCollectionsRoute
  OpsComplianceReadinessQueueRoute: typeof OpsComplianceReadinessQueueRoute
  OpsCreditReviewRoute: typeof OpsCreditReviewRoute
  OpsFleetAuditsRoute: typeof OpsFleetAuditsRoute
  OpsFleetRebalancingRoute: typeof OpsFleetRebalancingRoute
  OpsIncidentComplianceQueueRoute: typeof OpsIncidentComplianceQueueRoute
  OpsLienDeadlinesRoute: typeof OpsLienDeadlinesRoute
  OpsRevenueRecognitionRoute: typeof OpsRevenueRecognitionRoute
  OpsShopMorningQueueRoute: typeof OpsShopMorningQueueRoute
  OpsTechnicianMorningQueueRoute: typeof OpsTechnicianMorningQueueRoute
  OpsTransfersRoute: typeof OpsTransfersRoute
  PortalRequestsRoute: typeof PortalRequestsRoute
  PortalStorefrontRoute: typeof PortalStorefrontRoute
  RentalAvailabilityRoute: typeof RentalAvailabilityRoute
  RentalCatalogRoute: typeof RentalCatalogRoute
  RentalCounterReviewRoute: typeof RentalCounterReviewRoute
  RentalInspectionComparisonRoute: typeof RentalInspectionComparisonRoute
  RentalPortalFinancialsRoute: typeof RentalPortalFinancialsRoute
  RentalProjectProposalRoute: typeof RentalProjectProposalRoute
  RentalQuotingRoute: typeof RentalQuotingRoute
  RentalReturnsRoute: typeof RentalReturnsRoute
  StorefrontCartRoute: typeof StorefrontCartRoute
  OpsIndexRoute: typeof OpsIndexRoute
  CrmCustomersIdRoute: typeof CrmCustomersIdRoute
  EntitiesEntityTypeIdRoute: typeof EntitiesEntityTypeIdRoute
  OpsAuditEntityIdRoute: typeof OpsAuditEntityIdRoute
  OpsFindingsFindingIdRoute: typeof OpsFindingsFindingIdRoute
  PortalBillingUpdateTokenIdRoute: typeof PortalBillingUpdateTokenIdRoute
  PortalCatalogJobSiteIdRoute: typeof PortalCatalogJobSiteIdRoute
  PortalIntakeTokenIdRoute: typeof PortalIntakeTokenIdRoute
  PortalScheduleContractIdRoute: typeof PortalScheduleContractIdRoute
  RentalContractsIdRoute: typeof RentalContractsIdRoute
  RentalOrdersIdRoute: typeof RentalOrdersIdRoute
  CrmCustomersIndexRoute: typeof CrmCustomersIndexRoute
  EntitiesEntityTypeIndexRoute: typeof EntitiesEntityTypeIndexRoute
  OpsFindingsIndexRoute: typeof OpsFindingsIndexRoute
  RentalContractsIndexRoute: typeof RentalContractsIndexRoute
  RentalOrdersIndexRoute: typeof RentalOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/cart': {
      id: '/storefront/cart'
      path: '/storefront/cart'
      fullPath: '/storefront/cart'
      preLoaderRoute: typeof StorefrontCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/returns': {
      id: '/rental/returns'
      path: '/rental/returns'
      fullPath: '/rental/returns'
      preLoaderRoute: typeof RentalReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/quoting': {
      id: '/rental/quoting'
      path: '/rental/quoting'
      fullPath: '/rental/quoting'
      preLoaderRoute: typeof RentalQuotingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/project-proposal': {
      id: '/rental/project-proposal'
      path: '/rental/project-proposal'
      fullPath: '/rental/project-proposal'
      preLoaderRoute: typeof RentalProjectProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/portal-financials': {
      id: '/rental/portal-financials'
      path: '/rental/portal-financials'
      fullPath: '/rental/portal-financials'
      preLoaderRoute: typeof RentalPortalFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/inspection-comparison': {
      id: '/rental/inspection-comparison'
      path: '/rental/inspection-comparison'
      fullPath: '/rental/inspection-comparison'
      preLoaderRoute: typeof RentalInspectionComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/counter-review': {
      id: '/rental/counter-review'
      path: '/rental/counter-review'
      fullPath: '/rental/counter-review'
      preLoaderRoute: typeof RentalCounterReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/catalog': {
      id: '/rental/catalog'
      path: '/rental/catalog'
      fullPath: '/rental/catalog'
      preLoaderRoute: typeof RentalCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/availability': {
      id: '/rental/availability'
      path: '/rental/availability'
      fullPath: '/rental/availability'
      preLoaderRoute: typeof RentalAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/storefront': {
      id: '/portal/storefront'
      path: '/portal/storefront'
      fullPath: '/portal/storefront'
      preLoaderRoute: typeof PortalStorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/requests': {
      id: '/portal/requests'
      path: '/portal/requests'
      fullPath: '/portal/requests'
      preLoaderRoute: typeof PortalRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/transfers': {
      id: '/ops/transfers'
      path: '/ops/transfers'
      fullPath: '/ops/transfers'
      preLoaderRoute: typeof OpsTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/technician-morning-queue': {
      id: '/ops/technician-morning-queue'
      path: '/ops/technician-morning-queue'
      fullPath: '/ops/technician-morning-queue'
      preLoaderRoute: typeof OpsTechnicianMorningQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/shop-morning-queue': {
      id: '/ops/shop-morning-queue'
      path: '/ops/shop-morning-queue'
      fullPath: '/ops/shop-morning-queue'
      preLoaderRoute: typeof OpsShopMorningQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/revenue-recognition': {
      id: '/ops/revenue-recognition'
      path: '/ops/revenue-recognition'
      fullPath: '/ops/revenue-recognition'
      preLoaderRoute: typeof OpsRevenueRecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/lien-deadlines': {
      id: '/ops/lien-deadlines'
      path: '/ops/lien-deadlines'
      fullPath: '/ops/lien-deadlines'
      preLoaderRoute: typeof OpsLienDeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/incident-compliance-queue': {
      id: '/ops/incident-compliance-queue'
      path: '/ops/incident-compliance-queue'
      fullPath: '/ops/incident-compliance-queue'
      preLoaderRoute: typeof OpsIncidentComplianceQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/fleet-rebalancing': {
      id: '/ops/fleet-rebalancing'
      path: '/ops/fleet-rebalancing'
      fullPath: '/ops/fleet-rebalancing'
      preLoaderRoute: typeof OpsFleetRebalancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/fleet-audits': {
      id: '/ops/fleet-audits'
      path: '/ops/fleet-audits'
      fullPath: '/ops/fleet-audits'
      preLoaderRoute: typeof OpsFleetAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/credit-review': {
      id: '/ops/credit-review'
      path: '/ops/credit-review'
      fullPath: '/ops/credit-review'
      preLoaderRoute: typeof OpsCreditReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/compliance-readiness-queue': {
      id: '/ops/compliance-readiness-queue'
      path: '/ops/compliance-readiness-queue'
      fullPath: '/ops/compliance-readiness-queue'
      preLoaderRoute: typeof OpsComplianceReadinessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/collections': {
      id: '/ops/collections'
      path: '/ops/collections'
      fullPath: '/ops/collections'
      preLoaderRoute: typeof OpsCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/billing-updates': {
      id: '/ops/billing-updates'
      path: '/ops/billing-updates'
      fullPath: '/ops/billing-updates'
      preLoaderRoute: typeof OpsBillingUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/account-health-queue': {
      id: '/ops/account-health-queue'
      path: '/ops/account-health-queue'
      fullPath: '/ops/account-health-queue'
      preLoaderRoute: typeof OpsAccountHealthQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/kits': {
      id: '/inventory/kits'
      path: '/inventory/kits'
      fullPath: '/inventory/kits'
      preLoaderRoute: typeof InventoryKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/calendar': {
      id: '/inventory/calendar'
      path: '/inventory/calendar'
      fullPath: '/inventory/calendar'
      preLoaderRoute: typeof InventoryCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/pod': {
      id: '/field/pod'
      path: '/field/pod'
      fullPath: '/field/pod'
      preLoaderRoute: typeof FieldPodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/mobile': {
      id: '/field/mobile'
      path: '/field/mobile'
      fullPath: '/field/mobile'
      preLoaderRoute: typeof FieldMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/dispatch': {
      id: '/field/dispatch'
      path: '/field/dispatch'
      fullPath: '/field/dispatch'
      preLoaderRoute: typeof FieldDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/counts': {
      id: '/field/counts'
      path: '/field/counts'
      fullPath: '/field/counts'
      preLoaderRoute: typeof FieldCountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive/monthly-operating-pack': {
      id: '/executive/monthly-operating-pack'
      path: '/executive/monthly-operating-pack'
      fullPath: '/executive/monthly-operating-pack'
      preLoaderRoute: typeof ExecutiveMonthlyOperatingPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/org-hierarchy': {
      id: '/enterprise/org-hierarchy'
      path: '/enterprise/org-hierarchy'
      fullPath: '/enterprise/org-hierarchy'
      preLoaderRoute: typeof EnterpriseOrgHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/yard': {
      id: '/dispatch/yard'
      path: '/dispatch/yard'
      fullPath: '/dispatch/yard'
      preLoaderRoute: typeof DispatchYardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/predispatch': {
      id: '/dispatch/predispatch'
      path: '/dispatch/predispatch'
      fullPath: '/dispatch/predispatch'
      preLoaderRoute: typeof DispatchPredispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/live': {
      id: '/dispatch/live'
      path: '/dispatch/live'
      fullPath: '/dispatch/live'
      preLoaderRoute: typeof DispatchLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/complaints': {
      id: '/dispatch/complaints'
      path: '/dispatch/complaints'
      fullPath: '/dispatch/complaints'
      preLoaderRoute: typeof DispatchComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/ops': {
      id: '/branch/ops'
      path: '/branch/ops'
      fullPath: '/branch/ops'
      preLoaderRoute: typeof BranchOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/morning-brief': {
      id: '/branch/morning-brief'
      path: '/branch/morning-brief'
      fullPath: '/branch/morning-brief'
      preLoaderRoute: typeof BranchMorningBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/monthly-pack': {
      id: '/branch/monthly-pack'
      path: '/branch/monthly-pack'
      fullPath: '/branch/monthly-pack'
      preLoaderRoute: typeof BranchMonthlyPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/counts': {
      id: '/branch/counts'
      path: '/branch/counts'
      fullPath: '/branch/counts'
      preLoaderRoute: typeof BranchCountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/transport': {
      id: '/analytics/transport'
      path: '/analytics/transport'
      fullPath: '/analytics/transport'
      preLoaderRoute: typeof AnalyticsTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/tax-filings': {
      id: '/analytics/tax-filings'
      path: '/analytics/tax-filings'
      fullPath: '/analytics/tax-filings'
      preLoaderRoute: typeof AnalyticsTaxFilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/safety': {
      id: '/analytics/safety'
      path: '/analytics/safety'
      fullPath: '/analytics/safety'
      preLoaderRoute: typeof AnalyticsSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/fleet': {
      id: '/analytics/fleet'
      path: '/analytics/fleet'
      fullPath: '/analytics/fleet'
      preLoaderRoute: typeof AnalyticsFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/enterprise-financials': {
      id: '/analytics/enterprise-financials'
      path: '/analytics/enterprise-financials'
      fullPath: '/analytics/enterprise-financials'
      preLoaderRoute: typeof AnalyticsEnterpriseFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/dashboards': {
      id: '/analytics/dashboards'
      path: '/analytics/dashboards'
      fullPath: '/analytics/dashboards'
      preLoaderRoute: typeof AnalyticsDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/ai-reporting': {
      id: '/analytics/ai-reporting'
      path: '/analytics/ai-reporting'
      fullPath: '/analytics/ai-reporting'
      preLoaderRoute: typeof AnalyticsAiReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/general-ledger': {
      id: '/accounting/general-ledger'
      path: '/accounting/general-ledger'
      fullPath: '/accounting/general-ledger'
      preLoaderRoute: typeof AccountingGeneralLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/export-config': {
      id: '/accounting/export-config'
      path: '/accounting/export-config'
      fullPath: '/accounting/export-config'
      preLoaderRoute: typeof AccountingExportConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/orders/': {
      id: '/rental/orders/'
      path: '/rental/orders'
      fullPath: '/rental/orders/'
      preLoaderRoute: typeof RentalOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/contracts/': {
      id: '/rental/contracts/'
      path: '/rental/contracts'
      fullPath: '/rental/contracts/'
      preLoaderRoute: typeof RentalContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/findings/': {
      id: '/ops/findings/'
      path: '/ops/findings'
      fullPath: '/ops/findings/'
      preLoaderRoute: typeof OpsFindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/': {
      id: '/entities/$entityType/'
      path: '/entities/$entityType'
      fullPath: '/entities/$entityType/'
      preLoaderRoute: typeof EntitiesEntityTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers/': {
      id: '/crm/customers/'
      path: '/crm/customers'
      fullPath: '/crm/customers/'
      preLoaderRoute: typeof CrmCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/orders/$id': {
      id: '/rental/orders/$id'
      path: '/rental/orders/$id'
      fullPath: '/rental/orders/$id'
      preLoaderRoute: typeof RentalOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/contracts/$id': {
      id: '/rental/contracts/$id'
      path: '/rental/contracts/$id'
      fullPath: '/rental/contracts/$id'
      preLoaderRoute: typeof RentalContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/schedule/$contractId': {
      id: '/portal/schedule/$contractId'
      path: '/portal/schedule/$contractId'
      fullPath: '/portal/schedule/$contractId'
      preLoaderRoute: typeof PortalScheduleContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/intake/$tokenId': {
      id: '/portal/intake/$tokenId'
      path: '/portal/intake/$tokenId'
      fullPath: '/portal/intake/$tokenId'
      preLoaderRoute: typeof PortalIntakeTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/catalog/$jobSiteId': {
      id: '/portal/catalog/$jobSiteId'
      path: '/portal/catalog/$jobSiteId'
      fullPath: '/portal/catalog/$jobSiteId'
      preLoaderRoute: typeof PortalCatalogJobSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/billing-update/$tokenId': {
      id: '/portal/billing-update/$tokenId'
      path: '/portal/billing-update/$tokenId'
      fullPath: '/portal/billing-update/$tokenId'
      preLoaderRoute: typeof PortalBillingUpdateTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/findings/$findingId': {
      id: '/ops/findings/$findingId'
      path: '/ops/findings/$findingId'
      fullPath: '/ops/findings/$findingId'
      preLoaderRoute: typeof OpsFindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/audit/$entityId': {
      id: '/ops/audit/$entityId'
      path: '/ops/audit/$entityId'
      fullPath: '/ops/audit/$entityId'
      preLoaderRoute: typeof OpsAuditEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$id': {
      id: '/entities/$entityType/$id'
      path: '/entities/$entityType/$id'
      fullPath: '/entities/$entityType/$id'
      preLoaderRoute: typeof EntitiesEntityTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers/$id': {
      id: '/crm/customers/$id'
      path: '/crm/customers/$id'
      fullPath: '/crm/customers/$id'
      preLoaderRoute: typeof CrmCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AccountingExportConfigRoute: AccountingExportConfigRoute,
  AccountingGeneralLedgerRoute: AccountingGeneralLedgerRoute,
  AnalyticsAiReportingRoute: AnalyticsAiReportingRoute,
  AnalyticsDashboardsRoute: AnalyticsDashboardsRoute,
  AnalyticsEnterpriseFinancialsRoute: AnalyticsEnterpriseFinancialsRoute,
  AnalyticsFleetRoute: AnalyticsFleetRoute,
  AnalyticsSafetyRoute: AnalyticsSafetyRoute,
  AnalyticsTaxFilingsRoute: AnalyticsTaxFilingsRoute,
  AnalyticsTransportRoute: AnalyticsTransportRoute,
  BranchCountsRoute: BranchCountsRoute,
  BranchMonthlyPackRoute: BranchMonthlyPackRoute,
  BranchMorningBriefRoute: BranchMorningBriefRoute,
  BranchOpsRoute: BranchOpsRoute,
  DispatchComplaintsRoute: DispatchComplaintsRoute,
  DispatchLiveRoute: DispatchLiveRoute,
  DispatchPredispatchRoute: DispatchPredispatchRoute,
  DispatchYardRoute: DispatchYardRoute,
  EnterpriseOrgHierarchyRoute: EnterpriseOrgHierarchyRoute,
  ExecutiveMonthlyOperatingPackRoute: ExecutiveMonthlyOperatingPackRoute,
  FieldCountsRoute: FieldCountsRoute,
  FieldDispatchRoute: FieldDispatchRoute,
  FieldMobileRoute: FieldMobileRoute,
  FieldPodRoute: FieldPodRoute,
  InventoryCalendarRoute: InventoryCalendarRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  InventoryKitsRoute: InventoryKitsRoute,
  OpsAccountHealthQueueRoute: OpsAccountHealthQueueRoute,
  OpsBillingUpdatesRoute: OpsBillingUpdatesRoute,
  OpsCollectionsRoute: OpsCollectionsRoute,
  OpsComplianceReadinessQueueRoute: OpsComplianceReadinessQueueRoute,
  OpsCreditReviewRoute: OpsCreditReviewRoute,
  OpsFleetAuditsRoute: OpsFleetAuditsRoute,
  OpsFleetRebalancingRoute: OpsFleetRebalancingRoute,
  OpsIncidentComplianceQueueRoute: OpsIncidentComplianceQueueRoute,
  OpsLienDeadlinesRoute: OpsLienDeadlinesRoute,
  OpsRevenueRecognitionRoute: OpsRevenueRecognitionRoute,
  OpsShopMorningQueueRoute: OpsShopMorningQueueRoute,
  OpsTechnicianMorningQueueRoute: OpsTechnicianMorningQueueRoute,
  OpsTransfersRoute: OpsTransfersRoute,
  PortalRequestsRoute: PortalRequestsRoute,
  PortalStorefrontRoute: PortalStorefrontRoute,
  RentalAvailabilityRoute: RentalAvailabilityRoute,
  RentalCatalogRoute: RentalCatalogRoute,
  RentalCounterReviewRoute: RentalCounterReviewRoute,
  RentalInspectionComparisonRoute: RentalInspectionComparisonRoute,
  RentalPortalFinancialsRoute: RentalPortalFinancialsRoute,
  RentalProjectProposalRoute: RentalProjectProposalRoute,
  RentalQuotingRoute: RentalQuotingRoute,
  RentalReturnsRoute: RentalReturnsRoute,
  StorefrontCartRoute: StorefrontCartRoute,
  OpsIndexRoute: OpsIndexRoute,
  CrmCustomersIdRoute: CrmCustomersIdRoute,
  EntitiesEntityTypeIdRoute: EntitiesEntityTypeIdRoute,
  OpsAuditEntityIdRoute: OpsAuditEntityIdRoute,
  OpsFindingsFindingIdRoute: OpsFindingsFindingIdRoute,
  PortalBillingUpdateTokenIdRoute: PortalBillingUpdateTokenIdRoute,
  PortalCatalogJobSiteIdRoute: PortalCatalogJobSiteIdRoute,
  PortalIntakeTokenIdRoute: PortalIntakeTokenIdRoute,
  PortalScheduleContractIdRoute: PortalScheduleContractIdRoute,
  RentalContractsIdRoute: RentalContractsIdRoute,
  RentalOrdersIdRoute: RentalOrdersIdRoute,
  CrmCustomersIndexRoute: CrmCustomersIndexRoute,
  EntitiesEntityTypeIndexRoute: EntitiesEntityTypeIndexRoute,
  OpsFindingsIndexRoute: OpsFindingsIndexRoute,
  RentalContractsIndexRoute: RentalContractsIndexRoute,
  RentalOrdersIndexRoute: RentalOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
