apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-datasource-prometheus
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    {{ .Values.grafana.datasourceLabel }}: {{ .Values.grafana.datasourceLabelValue | quote }}
data:
  datasource-prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: {{ .Values.grafana.prometheusUrl | quote }}
        access: proxy
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          httpMethod: POST
